### ISSUE TITLE
New Mappy version appears to prevent installation

### ISSUE THREAD

**Issue by Desperate-Dan** [polio-nanopore/piranha#128]
Hello! Just tried to install piranha on a new machine and the pip install command was failing with the following `ERROR: Could not build wheels for mappy, which is required to install pyproject.toml-based projects`. It appears this is for some reason due to update of mappy to 2.25 (happened about 12 hours ago as of writing). Pinning the version of mappy to 2.24 in setup.py seems to get around this issue at the moment.

**Comment by rmcolq** [comment]
Appears to be fixed with mappy 2.26 with no update to setup.py
