### ISSUE TITLE
Accessibility of fastq_pass folder at default location

### ISSUE THREAD

**Issue by ebujaki** [polio-nanopore/piranha#129]
Hi,
Would it be possible to ensure piranha can access the default location of fastq_pass folder on /var/lib/minknow/data.. please?
Thanks

**Comment by rmcolq** [comment]
In which way can it not - is it a permissions error for that directory, or do you want a default location of the fastq_pass to be there?

**Comment by ebujaki** [comment]
Hi, 
Please see attached pics. It looks like a permission issue.

![20230620_105642](https://github.com/polio-nanopore/piranha/assets/126177398/f550a1d0-9fcd-40bf-af83-d1aa1e374e9e)
![20230620_105731](https://github.com/polio-nanopore/piranha/assets/126177398/383273bd-24f2-4377-8662-41c633b0e902)

**Comment by rmcolq** [comment]
If it is a permission error, that suggests that the permissions settings on your computer for that directory are not giving read access to the process. This isn't an error with the snakemake but with the setup on the computer. What does the output of `ls -ltr /var/lib/minknow/data` (or the full path to file) look like?

**Comment by aineniamh** [comment]
I'm going to close this as I assume it got resolved without follow up. Will reopen again if needed!
