### ISSUE TITLE
Applied analysis options shown in output?

### ISSUE THREAD

**Issue by ebujaki** [polio-nanopore/piranha#130]
Hi,
Are the applied analysis options shown somewhere in the output? It would be handy for a number of reasons.
Thanks

**Comment by rmcolq** [comment]
I think most of this info was available in verbose mode, but you can now use the `--save-config` flag to save a copy of all the parameters used at runtime to the output directory. This can be read in as input to repeat the analysis later.

NB to future selves: should check if any of the config keys which are ignored should instead be provided as defaults in the list and overwritten
