### ISSUE TITLE
unable to detect fastQ files during analysis

### ISSUE THREAD

**Issue by ShadrackBar** [polio-nanopore/piranha#140]
<img width="650" alt="Screenshot 2023-07-28 213404" src="https://github.com/polio-nanopore/piranha/assets/140058630/dc6ecebf-29c1-4aa9-8150-1edc3c4fe4b6">

my analysis is unable to detect fastQ files.

**Comment by rmcolq** [comment]
You you give us some information about the directory structure for your sequencing run directory by comparison with this?

https://github.com/polio-nanopore/piranha#what-should-my-readsread-directory-look-like
The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336. Is e buidheann carthannais a th’ ann an Oilthigh Dhùn Èideann, clàraichte an Alba, àireamh clàraidh SC005336.

**Comment by aineniamh** [comment]
I'm going to close this as there has been no response from @ShadrackBar - will open again if they come back with more info
