### ISSUE TITLE
Piranha crashing after latest update

### ISSUE THREAD

**Issue by AShaw1802** [polio-nanopore/piranha#162]
Hi,
I've just been running PIRANHA with the test data after the latest update and it keeps crashing at generate_report:
Error in rule generate_report:
    jobid: 0
    input: /data/run_data/output/piranha_output/published_data/vp1_sequences.fasta, /tmp/tmpmve3kmel/barcode07/variation_info.json, /tmp/tmpmve3kmel/barcode07/masked_variants.csv, /tmp/tmpmve3kmel/barcode07/variants.csv, /tmp/tmpmve3kmel/preprocessing_config.yaml
    output: /data/run_data/output/piranha_output/barcode_reports/barcode07_report.html

I haven't been able to test this on another laptop as I've only one to hand, but could you please check if this is a general issue?
Thanks,
Alex

**Comment by aineniamh** [comment]
Could you provide the test data and what command you ran, and I'll run it here, because piranha is passing tests on the repo so it can run, but may be some edge case breaking!

**Comment by AShaw1802** [comment]
[Test.zip](https://github.com/polio-nanopore/piranha/files/13070076/Test.zip)
I'm using the test data from Piranha (attached), but running it in the GUI which I think we may have narrowed down the problem to- Catherine has now also had the same problem with the GUI. The GUI just updated Piranha this morning, which is why I thought it might the the new edition from over the weekend. Maybe this is one for Corey instead?

**Comment by aineniamh** [comment]
Ah right! So the green tick that shows up on the piranha repo  means that github has tested piranha on the test data and managed to run to completion. I'm not sure what the exact GUI issue might be- but it could be a versioning issue of some sort. If it runs to the report, that suggests to me that mako might be causing an issue. 

@CorwinAnsley do you know what the issue might be?

**Comment by jolnack** [comment]
Hi,
Also run the updated Piranha on command line using some data and got similar error. Screenshot here. you might need to zoom in to see the message as it quite hard to read. 
![image](https://github.com/polio-nanopore/piranha/assets/99412112/5bfc1bda-507f-4605-828f-a539fa004d09)

**Comment by aineniamh** [comment]
What was the data you used? If you share it (even by email) I can help debug your first test case

**Comment by jolnack** [comment]
I couldn’t send the data via email even as compressed file as it is bigger than the server allows. I will send you the dropbox link to access it :)

**Comment by AShaw1802** [comment]
The data that I used is attached to my earlier message- it's Test.zip. It's the test data from the Piranha repository.

**Comment by aineniamh** [comment]
I believe this should be resolved now for Alex, will investigate what the issue for yours was @jolnack!
