### ISSUE TITLE
require fastq_pass at end of path in piranha GUI

### ISSUE THREAD

**Issue by cathrnbp** [polio-nanopore/piranha#186]
If reads are in barcode folders in the following path: /runs/run1/fastq_pass
If /runs/run1/fastq_pass is selected in piranha GUI, then piranha runs correctly.
But, it is possible to select /runs/run1 in the GUI, and piranha will run, finish, and produce a "detailed_run_report" full of 0 reads, apparently without issues.
Fix to require fastq_pass at end of path to ensure human error doesn't cause incorrect reporting of results.

**Comment by aineniamh** [comment]
Pinging @CorwinAnsley about this. 

My initial thought is that you might want more flexibility than forcing people to have 'fastq_pass' as the exact name- in case reads get moved somewhere etc- but for this use if you think reads will never be moved around, or directories will always be called this, then I guess it would be fine to require it.

**Comment by rambaut** [comment]
My thoughts on this - if the selected folder contains barcode folders then just use them. If not, look for the fastq_pass folder. If not there then fail or show message.

**Comment by aineniamh** [comment]
Resolved now- will break if no barcodes are identified, iterates through the directory and overwrites input readdir with the directory it finds the barcode files in. 

If you give it a VERY wrong input, like where all the minion runs are stored, it'll end up selecting the last one it iterates through and finds reads in.
