### ISSUE TITLE
Trivial - reduce the size of the tip dots in the phylogenetic tree

### ISSUE THREAD

**Issue by rambaut** [polio-nanopore/piranha#193]
The dots are very large and get big on roll over. I suggest perhaps 1/2 the current radius by default so you can better see the branches underneath. And they should only become 1.618 times bigger when rolled over.

**Comment by aineniamh** [comment]
Not hovered:
![Screenshot 2023-11-23 at 14 11 07](https://github.com/polio-nanopore/piranha/assets/11678307/0a32bf72-c598-4051-90a8-b02675d22a5d)
Hovered:
![Screenshot 2023-11-23 at 14 11 13](https://github.com/polio-nanopore/piranha/assets/11678307/6bb52fd2-3215-42c1-acb6-89bd215a823b)

this more what you're thinking?

**Comment by aineniamh** [comment]
on main now
