### ISSUE TITLE
Copy fastq data and barcodes CSV to output folder for storage and archiving

### ISSUE THREAD

**Issue by rambaut** [polio-nanopore/piranha#215]
It is likely that the `fastq.pass` data will need to be archived and stored long term. It would make sense if Piranha were to copy this to the output folder (or to another location) with a name and possibly other details for the run.

**Comment by aineniamh** [comment]
Done on main now, use `--archive-fastq` flag to trigger writing fastq_pass to outdir and use `--archivedir` if you want to overwrite the default output place and put them somewhere special.
