### ISSUE TITLE
Error when running haplotyping

### ISSUE THREAD

**Issue by CatherineTroman** [polio-nanopore/piranha#230]
I tried running the haplotyping with all default parameters on some samples where we were expecting a mixture of VDPV2 and nOPV2. It came up with the error message attached in a text file, I tried to understand it but wasn't really sure what was wrong.

[Haplotyping-error.txt](https://github.com/polio-nanopore/piranha/files/14696067/Haplotyping-error.txt)

If it would be useful I can send you the fastqs for that sample (too big to upload to this issue). It was the second sample it tried to process so not sure if it was to do with the sample or just running the haplotyping.

**Comment by ZoeVance** [comment]
There might be a useful error message buried in the log files but it could be a few layers deep. Probably easiest to send on the fastqs that are giving the error and I can troubleshoot from there!

**Comment by ZoeVance** [comment]
The error was caused by some missing error handling for sequences that have too few variants called to run haplotyping. Have added this in and should be good to go now!
