### ISSUE TITLE
Error during consensus building v1.2.3

### ISSUE THREAD

**Issue by CatherineTroman** [polio-nanopore/piranha#236]
We are currently running a training workshop and have found that every laptop with the GUI v1.5.3 running piranha v1.2.3 stops the analysis prematurely with an error during the consensus building step. 

I have attached the error as a text file and also the log file from the GUI just in case that might help. If you need any other details please do let me know.

Many thanks, Catherine

[consensus-error-piranha.txt](https://github.com/user-attachments/files/15901031/consensus-error-piranha.txt)

[log.txt](https://github.com/user-attachments/files/15901035/log.txt)

**Comment by rmcolq** [comment]
I'm taking a look with a fresh install here

**Comment by aineniamh** [comment]
Corey and I are chatting about this too- there was an issue a few days ago that Corey tried to fix because the Docker was not building correctly. I think tensorflow is the culprit

**Comment by aineniamh** [comment]
currently trying to rebuild the docker image and push as it seems to be working locally for corey

**Comment by aineniamh** [comment]
If you try run again, the latest docker image should be downgraded (thanks @rmcolq and @CorwinAnsley). Hopefully this should be a temp fix!

**Comment by CatherineTroman** [comment]
Perfect, thank you!

**Comment by aineniamh** [comment]
Hey @CatherineTroman, when is the workshop until? @rmcolq has potentially solved the issue with the Docker container and we could merge in and test, but don't want to break anything if you're still running the workshop. I'll merge in if you are finished with the installation in the workshop. Theoretically it should work and it'll mean all the latest features are available, but there is always a chance something unforeseen will break!

**Comment by CatherineTroman** [comment]
Sorry for the slow response, the workshop finished on Friday so you are welcome to merge in!

**Comment by aineniamh** [comment]
Closing here as docker image resolved
