### ISSUE TITLE
Read Counts in Report exceed read counts in input file

### ISSUE THREAD

**Issue by DarianHole** [polio-nanopore/piranha#66]
Hi @aineniamh,

Thanks for writing this software! We are currently validating it to use as a part of our Polio surveillance system and it works fantastically and provides a great visual/interactive html file that we can share! 

### Current Issue

Read counts from the preprocessing step are sometimes more than the total reads put into the program (seems to go with #40 but from what I've seen it is mostly affecting the non-polio enterovirus counts) and the unmapped part of the table is currently always coming out as 1. To test I am running with no size filtering at the moment (min 200, max 8000) instead of the default parameters so that could potentially be part of the reason.

### Some Troubleshooting I've Looked At

Dataset: https://www.ebi.ac.uk/ena/browser/view/PRJEB37193?show=reads
From the following paper: https://journals.asm.org/doi/10.1128/JCM.00920-20
Table output by version piranha v1.0.1:
![image](https://user-images.githubusercontent.com/46600008/189753779-f495f9b6-9d8f-4e58-9956-2a35baeaf22e.png)

I looked more into `ES-08` as one of the samples with the biggest increase in read counts. It has 14,770 reads in the fastq file and in the preprocessing table (and report) it totals 18,681 reads. When I parse the PAF file, I get 3450 unmapped and 18680 mapped (so the 1 unmapped read is the difference in the counts and probably should be 3450 unmapped in the table)

Trying to troubleshoot where the difference is coming from I was looking at the minimap2 command and the PAF file. In the `initial_processing` directory. Here, some of the reads are mapping more than once (even though they should not be). I would guess that the `--secondary=no` is not removing these as they are being treated as supplementary alignments. The minimap2 docs are here but if they are supplementary, removing them is discouraged: https://github.com/lh3/minimap2/blob/cd9ccfa069a2cdbdaa97296e1927468982939c4f/FAQ.md#5-how-to-output-one-alignment-per-read

Some final info. The top 5 reads mapping more than once in the file are as follows:
| read_name | num_times_mapped |
| - | - |
| ERR4033238.4016 | 6 |
| ERR4033238.13167 | 6 |
| ERR4033238.14215 | 6 |
| ERR4033238.10469 | 6 |
| ERR4033238.8864 | 5 |

And looking at the top one read in BLAST and in the PAF file it is mapping to different Coxsackieviruses although some in very small parts. PAF: 
```
ERR4033238.4016	7853	5244	5638	-	CoxsackievirusA6_KP144339	906	226	610	66	394	0	tp:A:P	cm:i:5	s1:i:64	s2:i:64	dv:f:0.1814	rl:i:0
ERR4033238.4016	7853	7753	7851	-	CoxsackievirusA12_AB126210	1087	427	529	64	102	38	tp:A:P	cm:i:7	s1:i:63	s2:i:0	dv:f:0.0666	rl:i:0
ERR4033238.4016	7853	5543	5832	-	CoxsackievirusA6_AY421764	906	110	399	62	290	29	tp:A:P	cm:i:5	s1:i:62	s2:i:0	dv:f:0.1634	rl:i:0
ERR4033238.4016	7853	2436	2955	+	CoxsackievirusA24_EF026081	906	388	906	51	519	16	tp:A:P	cm:i:5	s1:i:51	s2:i:0	dv:f:0.1963	rl:i:0
ERR4033238.4016	7853	2	63	+	CoxsackievirusA12_AB126210	1087	427	488	44	61	6	tp:A:P	cm:i:5	s1:i:44	s2:i:0	dv:f:0.0584	rl:i:0
ERR4033238.4016	7853	4994	5599	-	CoxsackievirusA6_LC126149	906	251	845	45	605	3	tp:A:P	cm:i:3	s1:i:43	s2:i:0	dv:f:0.2431	rl:i:0
```

Sorry this was a bit of a ramble, I am basically looking for the total reads to match the report table and whether you think this is a size selection issue or a mapping/parsing change that might need to be made?

Thanks,
Darian

**Comment by aineniamh** [comment]
Hi @DarianHole, thank you so much for flagging and leaving such a detailed issue post. I think you're right and have gotten to the bottom of the issue, that there are reads split across closely related references in the database. Post-processing within piranha, we bin reads into broader categories than the specific reference they've hit, so reads shouldn't be duplicated in the actual consensus calling step (I say shouldn't, I'll double check this), but if this background reference set is actually causing an issue we can change this. 

There's actually another issue (#40) that I've been meaning to test a single representative for each of the non-polio ev's and how this affects mapping etc. I think this will be linked to the issue you've flagged too.

**Comment by aineniamh** [comment]
I think we actually came across a similar thing with [rampart](https://github.com/artic-network/rampart/blob/e7894fc2ea49eec95d98f3956b53bc968be1921e/default_protocol/pipelines/demux_map/rules/parse_paf.py#L247) and got around it by just taking one of the hits if the last hit is from the same read. I'll have a look at implementing something like this here. We don't want to be doubly counting the reads! 

The alternative would be we just provide a peared down database, but it doesn't elimitate the possibility that this could happen.

**Comment by aineniamh** [comment]
I believe this is resolved now in the latest release. Thanks again for flagging!

**Comment by DarianHole** [comment]
Thanks again @aineniamh!! Sorry I couldn't look too much more into it on my end other than the initial testing.

I'll do some more validation and testing on the updates when I am back next week Friday

Cheers!
