### ISSUE TITLE
Name suggestions for bioconda recipe

### ISSUE THREAD

**Issue by rpetit3** [polio-nanopore/piranha#89]
Hi @aineniamh 

I'm going to add this to bioconda (if that's ok with you!), but there is already a package named [piranha](https://bioconda.github.io/recipes/piranha/README.html). I was thinking of some alternates, but would like you to a have the ultimate say.

Ideas: `piranha-py`, `piranha-polio`, `piranha-ont`, `polio-piranha`, `nano-piranha`, `piranahs`

Cheers,
Robert

**Comment by aineniamh** [comment]
Ah, fantastic @rpetit3, I'd been intending to put it on soon! I think I'd lean towards `piranha-polio` as it's descriptive of the project!

**Comment by rpetit3** [comment]
`piranha-polio` it will be! I'll ping you when I create the Bioconda PR to make sure you agree with the version pinnings.

Thank you so much @aineniamh!

**Comment by rpetit3** [comment]
Should be all set now: https://github.com/bioconda/bioconda-recipes/pull/37887

**Comment by aineniamh** [comment]
Amazing! Thanks so much @rpetit3, I really appreciate it!

**Comment by rpetit3** [comment]
@aineniamh piranha is now available on Bioconda as `piranha-polio` 

I'm going to go ahead and close this.

Cheers,
Robert

**Comment by aineniamh** [comment]
Ah excellent thanks so much!
